APOSOR302273-5G = "https://www.avantorsciences.com/fr/fr/product/35034924/acide-triphnylactique-97?isCatNumSearch=true&searchedCatalogNumber=APOSOR302273-5G"
ACRO117150050 = "https://www.avantorsciences.com/fr/fr/product/2359766/acide-diphnylactique-99?isCatNumSearch=true&searchedCatalogNumber=ACRO117150050"
ACRO188150100 = "https://www.avantorsciences.com/fr/fr/product/2359728/acide-4-biphnylactique-98?isCatNumSearch=true&searchedCatalogNumber=ACRO188150100"
